'use client';

import { useQuery } from '@tanstack/react-query';
import { apiClient } from '@/lib/api';
import type { PageDto, AboutSectionDto } from '@portfolio/shared';

export type RouteArea = 'public' | 'admin' | 'database' | 'redirect';

export type RouteCategory =
  | 'static_public'
  | 'admin_dashboard'
  | 'dynamic_page'
  | 'about_section'
  | 'route_pattern'
  | 'feed_system'
  | 'redirect';

export type RouteStatus =
  | 'active'
  | 'inactive'
  | 'published'
  | 'draft'
  | 'archived'
  | 'permanent_308'
  | 'temporary_302'
  | 'auth_guard';

export interface RouteItem {
  id: string;
  path: string;
  title: string;
  description: string;
  area: RouteArea;
  category: RouteCategory;
  source: string;
  status: RouteStatus;
  destinationUrl?: string;
  adminEditUrl?: string;
  isDynamic?: boolean;
}

// 1. Static Public & Feature Routes (All Public Core Pages & System Feeds)
const STATIC_PUBLIC_ROUTES: RouteItem[] = [
  {
    id: 'pub-home',
    path: '/',
    title: 'Homepage',
    description: 'Primary landing page with Hero, About, Skills, Featured Works, and Contact',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-about',
    path: '/about',
    title: 'About Overview',
    description: 'Personal background, engineering philosophy, and gateway to dynamic sections',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/about/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-works',
    path: '/works',
    title: 'Works & Projects Showcase',
    description: 'Filterable portfolio of engineering case studies, systems, and open source',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/works/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-blogs',
    path: '/blogs',
    title: 'Technical Writings & Blogs',
    description: 'Index of published engineering essays, architecture guides, and tutorials',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/blogs/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-research',
    path: '/research',
    title: 'Research Papers & Whitepapers',
    description: 'Academic publications, distributed systems research, and technical reports',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/research/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-skills',
    path: '/skills',
    title: 'Skills Matrix',
    description: 'Comprehensive taxonomy of technologies, frameworks, and architecture domains',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/skills/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-experience',
    path: '/experience',
    title: 'Work Experience',
    description: 'Overview of professional roles, companies, engineering leadership, and impacts',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/experience/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-education',
    path: '/education',
    title: 'Education & Academics',
    description: 'Academic qualifications, university degrees, coursework, and honors',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/education/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-timeline',
    path: '/my-timeline',
    title: 'Career & Journey Timeline',
    description: 'Chronological timeline of roles, milestones, and career achievements',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/my-timeline/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-certificates',
    path: '/certificates-achievements',
    title: 'Certificates & Achievements',
    description: 'Verified professional certifications, hackathon awards, and recognitions',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/certificates-achievements/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-resume',
    path: '/resume',
    title: 'Interactive Resume',
    description: 'Online verified resume with downloadable PDF and version details',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/resume/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-contact',
    path: '/contact',
    title: 'Contact & Inquiries',
    description: 'Direct contact form, messaging channels, and availability status',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/contact/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-opensource',
    path: '/opensource',
    title: 'Open Source Contributions',
    description: 'Public packages, GitHub repositories, and open source contributions',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/opensource/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-testimonials',
    path: '/testimonials',
    title: 'Client & Colleague Testimonials',
    description: 'Peer recommendations, client reviews, and professional endorsements',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/testimonials/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-gallery',
    path: '/gallery',
    title: 'Photography & Setup Gallery',
    description: 'Categorized photography, conference speaking, workspace, and setup photo gallery',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/gallery/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-guestbook',
    path: '/guestbook',
    title: 'Visitor Guestbook',
    description: 'Public visitor signatures and interactive guestbook wall',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/guestbook/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-newsletter',
    path: '/newsletter',
    title: 'Newsletter Archive',
    description: 'Published newsletter editions and subscriber signup portal',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/newsletter/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-newsletter-confirm',
    path: '/newsletter/confirm',
    title: 'Newsletter Subscription Confirmation',
    description: 'Double opt-in verification page for newsletter subscribers',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/newsletter/confirm/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-stats',
    path: '/stats',
    title: 'Live Portfolio Analytics',
    description: 'Public stats on visitor traffic, published projects, and engineering volume',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/stats/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-search',
    path: '/search',
    title: 'Global Search Console',
    description: 'Omnibox searching across projects, essays, skills, and site content',
    area: 'public',
    category: 'static_public',
    source: 'App Router (app/(public)/search/page.tsx)',
    status: 'active',
  },
  {
    id: 'pub-feed-xml',
    path: '/feed.xml',
    title: 'RSS Syndication Feed',
    description: 'Standard RSS 2.0 XML feed for blog syndication and readers',
    area: 'public',
    category: 'feed_system',
    source: 'Route Handler (app/feed.xml/route.ts)',
    status: 'active',
  },
  {
    id: 'pub-sitemap-xml',
    path: '/sitemap.xml',
    title: 'SEO XML Sitemap',
    description: 'Dynamic search engine sitemap containing all published site URLs',
    area: 'public',
    category: 'feed_system',
    source: 'Metadata Route (app/sitemap.ts)',
    status: 'active',
  },
  {
    id: 'pub-robots-txt',
    path: '/robots.txt',
    title: 'Crawler Directives (robots.txt)',
    description: 'Web spider indexing instructions and sitemap discovery pointers',
    area: 'public',
    category: 'feed_system',
    source: 'Metadata Route (app/robots.ts)',
    status: 'active',
  },
  {
    id: 'pub-og-image',
    path: '/opengraph-image',
    title: 'Dynamic OpenGraph Image Generator',
    description: 'Auto-generated Edge social preview image for rich links (1200x630)',
    area: 'public',
    category: 'feed_system',
    source: 'Image Response (app/opengraph-image.tsx)',
    status: 'active',
  },
  {
    id: 'pub-twitter-image',
    path: '/twitter-image',
    title: 'Dynamic Twitter Summary Card Generator',
    description: 'Auto-generated Edge preview card for Twitter/X social shares',
    area: 'public',
    category: 'feed_system',
    source: 'Image Response (app/twitter-image.tsx)',
    status: 'active',
  },
];

// 2. Dynamic Route Templates & Patterns (Excluded content item slugs like /blogs/some-slug are parameterized here)
const DYNAMIC_ROUTE_PATTERNS: RouteItem[] = [
  {
    id: 'pat-blog-slug',
    path: '/blogs/[slug]',
    title: 'Blog Article Case Study Pattern',
    description: 'Dynamic template rendering individual blog article by slug',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/blogs/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-blog-author',
    path: '/blogs/by/[author]',
    title: 'Author Articles Filter Pattern',
    description: 'Dynamic listing of articles filtered by author username',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/blogs/by/[author]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-blog-author-slug',
    path: '/blogs/by/[author]/[slug]',
    title: 'Author Article Permalink Pattern',
    description: 'Canonical multi-author permalink for an individual article',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/blogs/by/[author]/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-work-slug',
    path: '/works/[slug]',
    title: 'Project Case Study Pattern',
    description: 'Dynamic case study template for an individual project or system',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/works/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-work-author',
    path: '/works/by/[author]',
    title: 'Author Projects Filter Pattern',
    description: 'Listing of projects authored by a specific username',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/works/by/[author]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-work-author-slug',
    path: '/works/by/[author]/[slug]',
    title: 'Author Project Permalink Pattern',
    description: 'Canonical permalink for a project by a specific author',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/works/by/[author]/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-about-section',
    path: '/about/[section]',
    title: 'Dynamic About Sub-Section Pattern',
    description: 'Dynamic sub-page renderer for about sections configured in database',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/about/[section]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-experience-id',
    path: '/experience/[id]',
    title: 'Experience Detail Modal / Permalink Pattern',
    description: 'Deep link to specific role responsibilities and tech stack breakdown',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/experience/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-education-id',
    path: '/education/[id]',
    title: 'Education Detail Modal / Permalink Pattern',
    description: 'Deep link to specific degree achievements and coursework',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/education/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-research-slug',
    path: '/research/[slug]',
    title: 'Research Paper Reader Pattern',
    description: 'Dynamic reader and abstract viewer for an individual research paper',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/research/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'pat-page-slug',
    path: '/[slug]',
    title: 'Dynamic Custom Page Catch-All Pattern',
    description: 'Root catch-all route rendering dynamic markdown pages (e.g. /now, /uses)',
    area: 'public',
    category: 'route_pattern',
    source: 'App Router (app/(public)/[slug]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
];

// 3. Admin Dashboard URLs (All 42 CMS views and forms)
const ADMIN_ROUTES: RouteItem[] = [
  {
    id: 'adm-root',
    path: '/admin',
    title: 'Admin Dashboard Overview',
    description: 'Central CMS dashboard with live metrics, visitor trends, and quick actions',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-login',
    path: '/admin/login',
    title: 'Admin Authentication Portal',
    description: 'Secure admin login screen with JWT session issuance',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/login/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-analytics',
    path: '/admin/analytics',
    title: 'Visitor Analytics Console',
    description: 'Geographic traffic, page view heatmaps, browser stats, and visitor logs',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/analytics/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-activity',
    path: '/admin/activity',
    title: 'System Activity & Audit Trail',
    description: 'Comprehensive ledger of all administrative logins, content mutations, settings updates, and media operations',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/activity/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-works',
    path: '/admin/works',
    title: 'Projects & Works Manager',
    description: 'Manage case studies, project categorization, and live demo links',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/works/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-works-new',
    path: '/admin/works/new',
    title: 'Create Project Editor',
    description: 'Form and MDX editor for publishing a new portfolio project',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/works/new/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-works-edit',
    path: '/admin/works/[id]',
    title: 'Edit Project Editor Pattern',
    description: 'Full case study editor and metadata manager for an existing project',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/works/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'adm-blogs',
    path: '/admin/blogs',
    title: 'Blog Posts Manager',
    description: 'Manage technical articles, drafts, reading times, and publication schedules',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/blogs/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-blogs-new',
    path: '/admin/blogs/new',
    title: 'Create Blog Post Editor',
    description: 'Rich Markdown / MDX editor for authoring new technical articles',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/blogs/new/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-blogs-edit',
    path: '/admin/blogs/[id]',
    title: 'Edit Blog Post Editor Pattern',
    description: 'Markdown body, reading time recalculation, and SEO editor for a blog post',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/blogs/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'adm-research',
    path: '/admin/research',
    title: 'Research Papers Manager',
    description: 'Manage academic publications, DOI links, and attached PDF papers',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/research/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-research-new',
    path: '/admin/research/new',
    title: 'Create Research Paper Editor',
    description: 'Upload PDF and author abstract for new research paper',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/research/new/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-research-edit',
    path: '/admin/research/[id]',
    title: 'Edit Research Paper Editor Pattern',
    description: 'Modify abstract, DOI citation, PDF attachment, and publication status',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/research/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'adm-pages',
    path: '/admin/pages',
    title: 'Dynamic Markdown Pages Manager',
    description: 'Create and manage dynamic standalone pages (e.g. /now, /uses, /terms)',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/pages/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-pages-new',
    path: '/admin/pages/new',
    title: 'Create Dynamic Page Editor',
    description: 'Author custom standalone Markdown pages with slug assignment',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/pages/new/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-pages-edit',
    path: '/admin/pages/[id]',
    title: 'Edit Dynamic Page Editor Pattern',
    description: 'Editor for custom page content, SEO metadata, and slug modification',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/pages/[id]/page.tsx)',
    status: 'active',
    isDynamic: true,
  },
  {
    id: 'adm-blocks',
    path: '/admin/blocks',
    title: 'Content Blocks Builder',
    description: 'Manage modular page-builder content blocks and CTA widgets',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/blocks/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-profile',
    path: '/admin/profile',
    title: 'Author Profile Editor',
    description: 'Edit author biography, avatar, handle, and display name',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/profile/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-about',
    path: '/admin/about',
    title: 'About Sections Manager',
    description: 'Order and toggle visibility of dynamic /about/[section] sub-pages',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/about/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-skills',
    path: '/admin/skills',
    title: 'Skills Matrix & Categories',
    description: 'Add and organize technologies, proficiency levels, and skill domains',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/skills/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-experience',
    path: '/admin/experience',
    title: 'Work Experience Manager',
    description: 'Manage professional roles, companies, dates, and achievements',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/experience/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-education',
    path: '/admin/education',
    title: 'Education Records Manager',
    description: 'Manage university degrees, coursework, and institutions',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/education/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-timeline',
    path: '/admin/timeline',
    title: 'Journey & Timeline Events',
    description: 'Interactive timeline events, year milestones, and key achievements',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/timeline/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-certificates',
    path: '/admin/certificates',
    title: 'Certificates & Credentials',
    description: 'Upload certification badges, issuing organizations, and verification URLs',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/certificates/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-achievements',
    path: '/admin/achievements',
    title: 'Awards & Achievements Manager',
    description: 'Manage hackathon victories, competitions, awards, and recognitions',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/achievements/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-resume',
    path: '/admin/resume',
    title: 'Resume PDF Versions Manager',
    description: 'Upload versioned resume PDFs and designate the single active public resume',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/resume/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-tags',
    path: '/admin/tags',
    title: 'Taxonomy & Tags Manager',
    description: 'Global tag taxonomy applied across blogs, works, research, and dynamic pages',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/tags/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-social',
    path: '/admin/social',
    title: 'Social & Professional Links',
    description: 'Manage GitHub, LinkedIn, X, and other external social profiles',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/social/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-opensource',
    path: '/admin/opensource',
    title: 'Open Source Contributions Manager',
    description: 'Manage open source packages, repository stats, and contributions',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/opensource/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-testimonials',
    path: '/admin/testimonials',
    title: 'Testimonials & Recommendations',
    description: 'Manage client endorsements, peer quotes, and review ratings',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/testimonials/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-gallery',
    path: '/admin/gallery',
    title: 'Media Gallery Manager',
    description: 'Categorized photography, conference speaking, and setup photo gallery',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/gallery/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-homepage',
    path: '/admin/homepage',
    title: 'Homepage Builder & Customizer',
    description: 'Reorder sections, toggle visibility, and configure homepage layouts',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/homepage/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-navigation',
    path: '/admin/navigation',
    title: 'Header & Footer Navigation Menus',
    description: 'Manage navigation trees, nested dropdowns, badges, and hotkeys',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/navigation/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-settings',
    path: '/admin/settings',
    title: 'Site Configuration & Settings',
    description: 'Global site title, author availability status, brand keywords, and preferences',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/settings/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-seo',
    path: '/admin/seo',
    title: 'Global SEO Defaults',
    description: 'Default Open Graph cards, Twitter metadata, and structured JSON-LD schemas',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/seo/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-emails',
    path: '/admin/emails',
    title: 'Email Notification Templates',
    description: 'Customize auto-responder and admin notification transactional emails',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/emails/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-media',
    path: '/admin/media',
    title: 'Media Library & File Storage',
    description: 'Central media library for image uploads, PDF storage, and asset metadata',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/media/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-contact',
    path: '/admin/contact',
    title: 'Contact Form Submissions Inbox',
    description: 'Review visitor inquiries, mark read status, and manage incoming messages',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/contact/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-guestbook',
    path: '/admin/guestbook',
    title: 'Guestbook Moderation Queue',
    description: 'Moderate pending guestbook entries, approve, reject, or pin signatures',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/guestbook/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-newsletter',
    path: '/admin/newsletter',
    title: 'Newsletter Subscribers Manager',
    description: 'Manage newsletter subscriber list and export contacts',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/newsletter/page.tsx)',
    status: 'active',
  },
  {
    id: 'adm-routes',
    path: '/admin/routes',
    title: 'Routes Directory & URL Explorer',
    description: 'Centralized directory of all public, admin, dynamic, and redirected URLs',
    area: 'admin',
    category: 'admin_dashboard',
    source: 'Admin App Router (app/(admin)/admin/routes/page.tsx)',
    status: 'active',
  },
];

// 4. System Redirects & URL Aliases
const SYSTEM_REDIRECTS: RouteItem[] = [
  {
    id: 'red-rss',
    path: '/rss.xml',
    title: 'RSS Feed Alias Redirect',
    description: 'Legacy RSS XML path permanently redirects to /feed.xml',
    area: 'redirect',
    category: 'redirect',
    source: 'Route Handler (app/rss.xml/route.ts)',
    status: 'permanent_308',
    destinationUrl: '/feed.xml',
  },
  {
    id: 'red-admin-guard',
    path: '/admin',
    title: 'Unauthenticated Admin Auth Guard',
    description: 'Redirects unauthenticated visitors attempting to access /admin to /admin/login',
    area: 'redirect',
    category: 'redirect',
    source: 'Client Auth Guard (AdminAuthGuard.tsx)',
    status: 'auth_guard',
    destinationUrl: '/admin/login?redirect=/admin',
  },
  {
    id: 'red-login-auth',
    path: '/admin/login',
    title: 'Authenticated Login Bypass',
    description: 'Redirects already authenticated admins directly to the main dashboard',
    area: 'redirect',
    category: 'redirect',
    source: 'Client Page Guard (app/(admin)/admin/login/page.tsx)',
    status: 'auth_guard',
    destinationUrl: '/admin',
  },
  {
    id: 'red-resume-active',
    path: '/api/v1/resumes/active/download',
    title: 'Active Resume Download Endpoint',
    description: 'Redirects to the CDN / storage URL of the designated active public resume PDF',
    area: 'redirect',
    category: 'redirect',
    source: 'Express Controller (resume.controller.ts)',
    status: 'temporary_302',
    destinationUrl: '[Active Resume Media File URL]',
  },
  {
    id: 'red-research-pdf',
    path: '/api/v1/research/:slug/download',
    title: 'Research Paper PDF Download Redirect',
    description: 'Redirects to the uploaded PDF storage URL for a requested research paper',
    area: 'redirect',
    category: 'redirect',
    source: 'Express Controller (research.controller.ts)',
    status: 'temporary_302',
    destinationUrl: '[Attached Research Paper PDF URL]',
  },
];

export function useRoutesDirectory() {
  // 1. Fetch dynamic markdown pages from the database
  const pagesQuery = useQuery<{ data: PageDto[] }>({
    queryKey: ['admin-pages-routes'],
    queryFn: () => apiClient.get<{ data: PageDto[] }>('/pages/admin/all'),
  });

  // 2. Fetch dynamic about sections from the database
  const aboutSectionsQuery = useQuery<{ data: AboutSectionDto[] }>({
    queryKey: ['admin-about-sections-routes'],
    queryFn: () => apiClient.get<{ data: AboutSectionDto[] }>('/about-sections/admin/all'),
  });

  const isLoading = pagesQuery.isLoading || aboutSectionsQuery.isLoading;

  // 3. Transform database dynamic pages into RouteItems
  const dynamicPages: RouteItem[] = (pagesQuery.data?.data || []).map((page) => ({
    id: `db-page-${page.id}`,
    path: `/${page.slug}`,
    title: page.title,
    description: `Dynamic Markdown page rendered via catch-all /[slug] route (Status: ${page.status})`,
    area: 'database',
    category: 'dynamic_page',
    source: 'Database (pages table)',
    status: page.status as RouteStatus,
    adminEditUrl: `/admin/pages/${page.id}`,
    isDynamic: true,
  }));

  // 4. Transform dynamic about sections into RouteItems
  const dynamicAboutSections: RouteItem[] = (aboutSectionsQuery.data?.data || []).map((sec) => ({
    id: `db-about-${sec.id}`,
    path: `/about/${sec.slug}`,
    title: `About: ${sec.title}`,
    description: `Dynamic About sub-section rendered via /about/[section] route`,
    area: 'database',
    category: 'about_section',
    source: 'Database (about_sections table)',
    status: sec.isEnabled ? 'active' : 'inactive',
    adminEditUrl: `/admin/about/${sec.id}`,
    isDynamic: true,
  }));

  // 5. Combine all route catalogs
  const allRoutes: RouteItem[] = [
    ...STATIC_PUBLIC_ROUTES,
    ...DYNAMIC_ROUTE_PATTERNS,
    ...dynamicPages,
    ...dynamicAboutSections,
    ...ADMIN_ROUTES,
    ...SYSTEM_REDIRECTS,
  ];

  // 6. Aggregate Counts
  const counts = {
    total: allRoutes.length,
    public: STATIC_PUBLIC_ROUTES.length + DYNAMIC_ROUTE_PATTERNS.length,
    admin: ADMIN_ROUTES.length,
    database: dynamicPages.length + dynamicAboutSections.length,
    redirects: SYSTEM_REDIRECTS.length,
  };

  return {
    routes: allRoutes,
    counts,
    isLoading,
    refetch: () => {
      pagesQuery.refetch();
      aboutSectionsQuery.refetch();
    },
  };
}
